### ISSUE TITLE
Updated readme/setup

### ISSUE THREAD

**Issue by ewquon** [a2e-mmc/WRF-setups#6]
Can we update the README to document the `SWiFT_20131108_PertMethodsGroup` case, and if applicable, update `setup.sh` to perform preprocessing for this case?

**Comment by hawbecker** [comment]
Since this case is idealized, I don't think setup.sh will really be applicable (there is no downloading of IC/BC's, there is no running WPS, etc) but if it's wanted, I can strip it down to still create the correct directory setup / link the executables and what not.

Is the README going to just stay in this WRF-setups directory or will each case have its own README?

**Comment by ewquon** [comment]
@phawbeck Do the executables have to be linked? 

I'm referring to the main README.md, which is what shows up when you land on https://github.com/a2e-mmc/WRF-setups

**Comment by hawbecker** [comment]
"Have to"  - no. They can be copied over. But if any changes are made to the code, you'll need to make sure to re-copy over the executables.

I'll update the main README

**Comment by ewquon** [comment]
Instead of symlinks, why not just
`export PATH="/path/to/WRF/run:$PATH"`
and then just run `wrf.exe` instead of `./wrf.exe`

**Comment by hawbecker** [comment]
Why not links? Everything else is already linked.

**Comment by ewquon** [comment]
Links can break, and updating the path to wrf in the runscript is easy. Also keeps the run directory less cluttered... If symlinking is standard wrf practice then I'll drop it.

**Comment by hawbecker** [comment]
How would that work with multiple versions of WRF installed? Symlinks are standard practice in WRF and for me, when a link breaks, there's a good reason for it (e.g. the code didn't compile correctly) and it is a red flag that something needs to be done.

**Comment by ewquon** [comment]
You could just add the WRF version you want to use into the PATH (e.g., what happens when you do a `module load` in the HPC environment). Symlinks are fine too...

**Comment by ewquon** [comment]
Documentation update in https://github.com/a2e-mmc/WRF-setups/pull/7
